### ISSUE TITLE
what is function fixKafkaParams in kafka010/KafkaUtils.scala？

### ISSUE THREAD

**Issue by ShortFinger** [koeninger/kafka-exactly-once#15]
Hi,everyone, hi koeninger.sorry about making this issue in this project,because I realy don't know how to contact koeninger.
    I have some questions about kafka010:

    1.     In  KafkaUtils.scala at line 200,there is a function fixKafkaParams,this function is prevent issues on executors,forcing params into that params. Is that legacy code or experimental code ? what about other  params in kafka0.10.x ?

    2.     There is still have @Experimental annotation in codes.is this project stopped ?

Forgive my poor English. If someone see this issue please give me some answers.

**Comment by koeninger** [comment]
Questions about spark code are probably best directed to the spark mailing
lists.

fixKafkaParams is to prevent issues on executors caused by kafka params
that are not appropriate.  For instance, the kafka consumer on the executor
should not be auto-committing.  The driver consumer is responsible for
coordination, the executor consumers should only consume exactly the offset
ranges specified, without doing anything else.

Regarding @experimental, most of Databricks' attention is on structured
streaming at this point, not DStreams.

**Comment by ShortFinger** [comment]
Thank you for answering my qusetions. Now I konw fixKafkaParams.
Thank you.
